### ISSUE TITLE
Reduce stutter

### ISSUE THREAD

**Issue by watzon** [cadmiumcr/tokenizer#2]
Currently all tokenizer implementations have a class name ending in `Tokenizer`. This is pretty unnecessary if everything is instead under a `Tokenizer` module.

**Comment by rmarronnier** [comment]
This is right and inspiring for other parts of Cadmium as well (`stemmer`, `summarizer`).

I'll take care of `summarizer` this week-end. I'll tell you if I can fix `Tokenizer` next week.

**Comment by watzon** [comment]
Sounds great!

**Comment by rmarronnier** [comment]
ok, I'm on it. But do you want to keep the convenience methods name intact like : 

```crystal
tokenizer = Cadmium.agressive_tokenizer.new(lang: :es)
tokenizer.tokenize("hola yo me llamo eduardo y esudié ingeniería")
# => ["hola", "yo", "me", "llamo", "eduardo", "y", "esudié", "ingeniería"]
``` 

or change them to : 

```crystal
tokenizer = Cadmium.agressive.new(lang: :es)
tokenizer.tokenize("hola yo me llamo eduardo y esudié ingeniería")
# => ["hola", "yo", "me", "llamo", "eduardo", "y", "esudié", "ingeniería"]
```

**Comment by rmarronnier** [comment]
```bash
In lib/cadmium_util/src/cadmium/util/diacritics.cr:3:32

 3 | {base: "A", letters: Regex.new("\u0041\u24B6\uFF21\u00C0\u00C1\u00C2\u1EA6\u1EA4\u1EAA\u1EA8\u00C3\u0100\u0102\u1EB0\u1EAE\u1EB4\u1EB2\u0226\u01E0\u00C4\u01DE\u1EA2\u00C5\u01FA\u01CD\u0200\u0202\u1EA0\u1EAC\u1EB6\u1E00\u0104\u023A\u2C6F]/")},
                                ^--
Error: no overload matches 'Cadmium::Regex.new' with type String
```

I guess we can't rename `RegexTokenizer` to simply `Regex`...

What should be the new name ?

**Comment by rmarronnier** [comment]
Also, I realized why `Tokenizer` and `Stemmer` don't have their own modules : the name would conflict with the abstract class. That's why I used the name `AbstractSummarizer` to have a `Summarizer` module.  Maybe not the brighest idea ever, so if you have some tips, that'd be great :smile:

**Comment by watzon** [comment]
> ok, I'm on it. But do you want to keep the convenience methods name intact like :
> 
> ```crystal
> tokenizer = Cadmium.agressive_tokenizer.new(lang: :es)
> tokenizer.tokenize("hola yo me llamo eduardo y esudié ingeniería")
> # => ["hola", "yo", "me", "llamo", "eduardo", "y", "esudié", "ingeniería"]
> ```
> 
> or change them to :
> 
> ```crystal
> tokenizer = Cadmium.agressive.new(lang: :es)
> tokenizer.tokenize("hola yo me llamo eduardo y esudié ingeniería")
> # => ["hola", "yo", "me", "llamo", "eduardo", "y", "esudié", "ingeniería"]
> ```

I was thinking about that. What do you think? Personally I like keeping it the way things are.

> Also, I realized why Tokenizer and Stemmer don't have their own modules : the name would conflict with the abstract class. That's why I used the name AbstractSummarizer to have a Summarizer module. Maybe not the brighest idea ever, so if you have some tips, that'd be great :smile:

So what we could do is have all of the tokenizers be under the namespace of the abstract tokenizer class. It won't hurt anything. It's not a module, but that's alright.

**Comment by watzon** [comment]
As far as the regex tokenizer goes it's still ok to name it `Regex`. When referencing the Crystal `Regex` class from within, just use `::Regex`.

**Comment by rmarronnier** [comment]
> I was thinking about that. What do you think? Personally I like keeping it the way things are.

My thought too. `Cadmium.word.new` is not explicit to say the least.

> As far as the regex tokenizer goes it's still ok to name it Regex. When referencing the Crystal Regex class from within, just use ::Regex.

Didn't know that. Nice.
