### ISSUE TITLE
Merge Cadmium::Util::Sentence to Cadmium::Tokenizer::Sentence

### ISSUE THREAD

**Issue by rmarronnier** [cadmiumcr/tokenizer#9]
I just realized that Cadmium has two "Sentencizers" : 
- `Cadmium::Tokenizer::Sentence` which is used nowhere in Cadmium world, probably because it's too simplistic.
- `Cadmium::Util::Sentence` which deals with more exceptions and corner cases, mostly english based though. It's used in diffirent cadmium shards.

I propose we merge the code of the last one in `Cadmium::Tokenizer::Sentence`, in the way of the Pragmatic Tokenizer, allowing us to add language specific rules (the default being english of course).

Then we can get rid of `Cadmium::Util::Sentence`.

I can make both PRs and PRs to repos impacted by the change.

To be perfectly honest, I've been working on  `Corpus`, `Document`, `Sentence`, `Token` classes and I'd like to add them to `Cadmium::Util` and `Sentence` was name conflicting with my work :-p

I'll develop the rationale in a specific `Cadmium::Util` issue.

**Comment by watzon** [comment]
Sounds like a good plan to me. I totally forgot there was a second one of those

**Comment by rmarronnier** [comment]
Great ! I'll take care of  it
